name: 每日 DeepSeek 提交摘要

on:
  workflow_dispatch:

  schedule:
    - cron: '0 0 * * *'  # 00:00 UTC，即北京时间每天 08:00

env:
  TZ: Asia/Shanghai

jobs:
  daily-summary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 完整历史
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 赋予脚本执行权限
        run: |
          chmod +x .github/scripts/generate_summary.sh
          chmod +x .github/scripts/send_email.py

      - name: 生成提交摘要并调用 DeepSeek
        run: ./.github/scripts/generate_summary.sh
        env:
          DEEPSEEK_API_URL: ${{ secrets.DEEPSEEK_API_URL }}
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          DEEPSEEK_PROMPT: ${{ secrets.DEEPSEEK_PROMPT }}
          DEEPSEEK_MODEL: ${{ secrets.DEEPSEEK_MODEL }}  # 如果有

      - name: 通过 SMTP 发送带附件的邮件
        run: python ./.github/scripts/send_email.py
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}